# Generated by Django 4.2 on 2026-09-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=16)),
                ("age", models.IntegerField(default=2)),
            ],
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(default=2),
        ),
    ]
